spring:
  application:
    name: spring-boot-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: queue_demo
    other_name: queue_demo_2
  exchange:
    name: exchange_demo_2
  routing:
    key: routing_key_demo
    other_key: routing_key_demo_2
